# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bh5C17lEEv47KKsP9CfzbZ-JfR8Clw21
"""

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Select a Stock and Load Historical Data
stock_symbol = 'AAPL'  # Apple Inc.
data = yf.download(stock_symbol, start='2020-01-01', end='2023-01-01')
print(f"Loaded historical data for {stock_symbol}")
print(data.head())

# 2. Feature Engineering and Target Variable Creation
def create_features(df):
    df = df.copy()
    df['Open'] = df['Open'].astype(float)
    df['High'] = df['High'].astype(float)
    df['Low'] = df['Low'].astype(float)
    df['Close'] = df['Close'].astype(float)
    df['Volume'] = df['Volume'].astype(float)

    # Target variable: next day's closing price
    df['Target'] = df['Close'].shift(-1)

    # Features
    df['Open_Close_Diff'] = df['Open'] - df['Close']
    df['High_Low_Diff'] = df['High'] - df['Low']
    df['Daily_Return'] = df['Close'].pct_change()

    # Lagged features
    df['Close_Lag1'] = df['Close'].shift(1)
    df['Close_Lag5'] = df['Close'].shift(5)

    # Moving Averages
    df['MA5'] = df['Close'].rolling(window=5).mean()
    df['MA10'] = df['Close'].rolling(window=10).mean()

    # Drop rows with NaN values created by feature engineering
    df = df.dropna()
    return df

data_processed = create_features(data)
print("Processed data with engineered features:")
print(data_processed.head())

# 3. Split Data into Training and Testing Sets
X = data_processed.drop(['Target'], axis=1)
Y = data_processed['Target']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

# 4. Train a Linear Regression Model
model = LinearRegression()
model.fit(X_train, Y_train)

print("Linear Regression Model Trained Successfully.")

# 5. Evaluate the Model and Visualize Predictions
Y_pred = model.predict(X_test)

mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared: {r2:.4f}")

# Plotting actual vs predicted prices
plt.figure(figsize=(14, 7))
plt.plot(Y_test.index, Y_test, label='Actual Close Price', color='blue')
plt.plot(Y_test.index, Y_pred, label='Predicted Close Price', color='red', linestyle='--')
plt.title(f'Actual vs. Predicted Closing Prices for {stock_symbol}')
plt.xlabel('Date')
plt.ylabel('Close Price')
plt.legend()
plt.grid(True)
plt.show()